---
# Main site playbook for GAD Infrastructure
# This is the entry point for all infrastructure automation

- name: Deploy common configuration to all hosts
  import_playbook: common/system_setup.yml
  tags:
    - common
    - system

- name: Deploy and configure webservers
  import_playbook: webservers/deploy.yml
  tags:
    - webservers
    - nginx

- name: Configure database servers
  import_playbook: database/deploy.yml
  when: inventory_hostname in groups['database'] | default([])
  tags:
    - database

- name: Configure network devices
  import_playbook: network/configure.yml
  when: inventory_hostname in groups['network'] | default([])
  tags:
    - network

- name: Apply security hardening
  import_playbook: security/harden.yml
  when: security_hardening_enabled | default(false)
  tags:
    - security
    - hardening 