---
- name: Test Playbook
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Create test directory
      file:
        path: /tmp/ansible-test
        state: directory
        mode: '0755'

    - name: Create test file
      copy:
        content: |
          This is a test file created by Ansible
          Timestamp: {{ ansible_date_time.iso8601 }}
        dest: /tmp/ansible-test/test.txt
        mode: '0644'

    - name: Show system information
      debug:
        msg: "Running on {{ ansible_hostname }} with OS {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: List directory contents
      shell: ls -la /tmp/ansible-test
      register: dir_list

    - name: Show directory contents
      debug:
        var: dir_list.stdout_lines 