---
- name: Test Playbook
  hosts: localhost
  gather_facts: true
  vars:
    test_dir: "{{ playbook_base_path }}/test"
  tasks:
    - name: Check system information
      debug:
        msg: "Running on {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Check Ansible version
      command: ansible --version
      register: ansible_version
      changed_when: false

    - name: Display Ansible version
      debug:
        var: ansible_version.stdout_lines

    - name: Check if required directories exist
      stat:
        path: "{{ item }}"
      register: dir_check
      loop:
        - "{{ playbook_base_path }}"
        - "{{ playbook_base_path }}/inventory"
        - "{{ playbook_base_path }}/roles"

    - name: Display directory status
      debug:
        msg: "{{ item.path }} exists: {{ item.stat.exists }}"
      loop: "{{ dir_check.results }}"

    - name: Create test directory
      file:
        path: "{{ test_dir }}"
        state: directory
        mode: '0755'

    - name: Test file operations
      block:
        - name: Create test file
          copy:
            content: "Test successful at {{ ansible_date_time.iso8601 }}"
            dest: "{{ test_dir }}/test.txt"
            mode: '0644'
          register: test_file

        - name: Show test file result
          debug:
            msg: "Test file created at {{ test_file.dest }}"

        - name: Verify file permissions
          stat:
            path: "{{ test_file.dest }}"
          register: file_stat

        - name: Display file permissions
          debug:
            msg: "File permissions: {{ file_stat.stat.mode }}"

    - name: Test API connectivity
      block:
        - name: Check API health endpoint
          uri:
            url: "http://localhost:8080/health"
            method: GET
            status_code: 200
          register: api_health
          ignore_errors: yes

        - name: Display API health status
          debug:
            msg: "API health check: {{ 'Success' if api_health.status == 200 else 'Failed' }}"

    - name: Test environment variables
      block:
        - name: Check required environment variables
          shell: "echo ${{ item }}"
          register: env_check
          loop:
            - ANSIBLE_PLAYBOOK_PATH
            - ANSIBLE_REPO_URL
          changed_when: false
          ignore_errors: yes

        - name: Display environment variable status
          debug:
            msg: "{{ item.item }}: {{ 'Set' if item.rc == 0 else 'Not set' }}"
          loop: "{{ env_check.results }}"

    - name: Cleanup test files
      file:
        path: "{{ test_dir }}"
        state: absent
      when: cleanup | default(false)

    - name: Final status
      debug:
        msg: |
          Test Summary:
          - System: {{ ansible_distribution }} {{ ansible_distribution_version }}
          - Ansible: {{ ansible_version.stdout_lines[0] }}
          - API Health: {{ 'OK' if api_health.status == 200 else 'Failed' }}
          - Test Directory: {{ test_dir }}
          - Test File: {{ test_file.dest if test_file is defined else 'Not created' }} 